insert into tucha.person (id, name, address, city, phone, email, new_adoption_allowed, details, can_host, host_capacity, host_species, host_details) values (1, 'zé', 'rua', 'Mira', 9484339823, 'djndsjkn@dfjjdfks.pt', true, '', true, 2, 'cão', null);

insert into tucha.veterinary (id, name, address, details) values (1, 'dom bixo', 'Tocha', null);

insert into tucha.animal (id, name, species, gender, breed, extimated_age, size, color, physical_state, emotional_state, details, is_adoptable, is_adoptable_reason, received_by, received_from, received_date, received_reason, received_details, chip_code, is_sterilizated, sterilization_date, sterilization_by, sterilization_details, is_dead, death_date, death_reason) values (1, 'Tucha', 'cão', 1, 'laranja', 10, 'médio', 'castanho', 'está bem', 'está bem', 'RIP', true, null, 1, 1, null, null, null, 12345, true, null, 1, null, false, null, null);
insert into tucha.animal (id, name, species, gender, breed, extimated_age, size, color, physical_state, emotional_state, details, is_adoptable, is_adoptable_reason, received_by, received_from, received_date, received_reason, received_details, chip_code, is_sterilizated, sterilization_date, sterilization_by, sterilization_details, is_dead, death_date, death_reason) values (2, 'Lipinho', 'cão', 0, 'rafeiro', 10, 'médio', 'castanho', 'está bem', 'está bem', 'dfsdfsdfs', true, null, 1, 1, null, null, null, 12345, true, null, 1, null, false, null, null);
insert into tucha.animal (id, name, species, gender, breed, extimated_age, size, color, physical_state, emotional_state, details, is_adoptable, is_adoptable_reason, received_by, received_from, received_date, received_reason, received_details, chip_code, is_sterilizated, sterilization_date, sterilization_by, sterilization_details, is_dead, death_date, death_reason) values (3, 'Baixote', 'cão', 0, 'rafeiro', 10, 'médio', 'castanho', 'está bem', 'está bem', 'dfsdfsdfs', true, null, 1, 1, null, null, null, 12345, true, null, 1, null, false, null, null);
insert into tucha.animal (id, name, species, gender, breed, extimated_age, size, color, physical_state, emotional_state, details, is_adoptable, is_adoptable_reason, received_by, received_from, received_date, received_reason, received_details, chip_code, is_sterilizated, sterilization_date, sterilization_by, sterilization_details, is_dead, death_date, death_reason) values (4, 'Velhote', 'cão', 0, 'rafeiro', 10, 'médio', 'castanho', 'está bem', 'está bem', 'dfsdfsdfs', true, null, 1, 1, null, null, null, 12345, true, null, 1, null, false, null, null);
insert into tucha.animal (id, name, species, gender, breed, extimated_age, size, color, physical_state, emotional_state, details, is_adoptable, is_adoptable_reason, received_by, received_from, received_date, received_reason, received_details, chip_code, is_sterilizated, sterilization_date, sterilization_by, sterilization_details, is_dead, death_date, death_reason) values (5, 'Lucas', 'cão', 0, 'pastor alemão', 10, 'médio', 'castanho', 'está bem', 'está bem', 'dfsdfsdfs', true, null, 1, 1, null, null, null, 12345, true, null, 1, null, false, null, null);
insert into tucha.animal (id, name, species, gender, breed, extimated_age, size, color, physical_state, emotional_state, details, is_adoptable, is_adoptable_reason, received_by, received_from, received_date, received_reason, received_details, chip_code, is_sterilizated, sterilization_date, sterilization_by, sterilization_details, is_dead, death_date, death_reason) values (6, 'Santos', 'cão', 0, 'rafeiro', 10, 'médio', 'castanho', 'está bem', 'está bem', 'dfsdfsdfs', true, null, 1, 1, null, null, null, 12345, true, null, 1, null, false, null, null);
insert into tucha.animal (id, name, species, gender, breed, extimated_age, size, color, physical_state, emotional_state, details, is_adoptable, is_adoptable_reason, received_by, received_from, received_date, received_reason, received_details, chip_code, is_sterilizated, sterilization_date, sterilization_by, sterilization_details, is_dead, death_date, death_reason) values (7, 'Balu', 'cão', 0, 'rafeiro', 10, 'médio', 'castanho', 'está bem', 'está bem', 'dfsdfsdfs', true, null, 1, 1, null, null, null, 12345, true, null, 1, null, false, null, null);
insert into tucha.animal (id, name, species, gender, breed, extimated_age, size, color, physical_state, emotional_state, details, is_adoptable, is_adoptable_reason, received_by, received_from, received_date, received_reason, received_details, chip_code, is_sterilizated, sterilization_date, sterilization_by, sterilization_details, is_dead, death_date, death_reason) values (8, 'Flora', 'cão', 1, 'corgi', 10, 'médio', 'castanho', 'está bem', 'está bem', 'dfsdfsdfs', true, null, 1, 1, null, null, null, 12345, true, null, 1, null, false, null, null);
insert into tucha.animal (id, name, species, gender, breed, extimated_age, size, color, physical_state, emotional_state, details, is_adoptable, is_adoptable_reason, received_by, received_from, received_date, received_reason, received_details, chip_code, is_sterilizated, sterilization_date, sterilization_by, sterilization_details, is_dead, death_date, death_reason) values (9, 'Guri', 'cão', 0, 'rafeiro', 10, 'médio', 'castanho', 'está bem', 'está bem', 'dfsdfsdfs', true, null, 1, 1, null, null, null, 12345, true, null, 1, null, false, null, null);
insert into tucha.animal (id, name, species, gender, breed, extimated_age, size, color, physical_state, emotional_state, details, is_adoptable, is_adoptable_reason, received_by, received_from, received_date, received_reason, received_details, chip_code, is_sterilizated, sterilization_date, sterilization_by, sterilization_details, is_dead, death_date, death_reason) values (10, 'Isabel', 'cão', 1, 'rafeiro', 10, 'médio', 'castanho', 'está bem', 'está bem', 'dfsdfsdfs', true, null, 1, 1, null, null, null, 12345, true, null, 1, null, false, null, null);
insert into tucha.animal (id, name, species, gender, breed, extimated_age, size, color, physical_state, emotional_state, details, is_adoptable, is_adoptable_reason, received_by, received_from, received_date, received_reason, received_details, chip_code, is_sterilizated, sterilization_date, sterilization_by, sterilization_details, is_dead, death_date, death_reason) values (11, 'Charlie', 'cão', 1, 'rafeiro', 10, 'médio', 'castanho', 'está bem', 'está bem', 'dfsdfsdfs', true, null, 1, 1, null, null, null, 12345, true, null, 1, null, false, null, null);
